#!/bin/bash

./extract_features_training.py good1 9 1 1
#./extract_features_training.py good2 15 1
#./extract_features_training.py good3 15 1

./extract_features_training.py bad1 9 -1 -1
#./extract_features_training.py bad2 15 -1
#./extract_features_training.py bad3 60 -1


./extract_features_training.py diff1 9 1 -1
./extract_features_training.py diff2 9 1 -1
./extract_features_training.py diff3 9 1 -1
./extract_features_training.py diff4 9 1 -1


cat feature_diff1 feature_diff2 feature_good1 feature_diff3 feature_bad1 feature_diff4 > train_feature_data
cat target_diff1 target_diff2 target_good1 target_diff3 target_bad1 target_diff4 > train_target_data


cat target_diff1 target_diff2 target_diff3 target_diff4 > tot_diff
wc target_good1
wc tot_diff
wc target_bad1
rm -rf tot_dff


wc train_feature_data 
wc train_target_data 

mv train* ../
